midtermsitoy/urls.py
from django.contrib import admin
from django.urls import path, include
from post import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('post/', include('post.urls'))
]

post/urls.py
from django.urls import path
from . import views


app_name = 'post'
urlpatterns = [

    path('', views.index, name='index'),
    path('createpost/', views.createpost, name ='createpost'),



]

post/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length =100)
    date_created = models.DateTimeField('date created')
    date_updated = models.DateTimeField('date updated')
    content = models.TextField(max_length = 200)
    is_active = models.BooleanField(default = True)

    def __str__(self):
        return self.title



class Comment(models.Model):
    date_created = models.DateTimeField('date created')
    content = models.TextField(max_length = 200)
    post = models.ForeignKey(Post, on_delete = models.CASCADE, related_name = 'comments', null=True, blank=True)

post/forms.py
from django.forms import ModelForm
from .models import Post

class PostModelForm(ModelForm):
    class Meta:
        model = Post
        exclude = ['id']

post/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Post
from .forms import PostModelForm
from datetime import datetime


# Create your views here.

def index(request):
    context = {}
    posts = Post.objects.all()

    context['posts'] = posts
    return render(request,'index.html', context)


def details(request, post_id):
    context = {}

    context['posts'] = Post.objects.get(id=question_id)

    return render(request, 'detail.html', context)


def createpost(request):
    context ={}

    if request.method == 'POST':
        form = PostModelForm(request.POST)
        if form.is_valid():
            form.save()
            return index(request)
        else:
            context['form'] = form
            return render(request, 'createpost.html', context)
    else:
         context['form'] = PostModelForm(initial={'date_created': datetime.now().date()})
         return render(request, 'createpost.html', context)

post/templates/base.html
{% load static %}
<html>
  <head>
    <title>
      {% block head %}
        this is the title <head>
      {% endblock %}
    </title>

    <link rel="stylesheet" type="text/css" href="{% static 'post/materialize/css/materialize.min.css' %}">
    {% block styles %}
    {% endblock %}
  </head>

  <body>
    {% block body %}
    123455
    {% endblock %}
    <script src = "{static 'post/materialize/js/materialize.min.js'}"> </script>
    {% block scripters %}
    {% endblock %}
  </body>
</html>

post/templates/createpost.html
{% extends 'base.html' %}

{% block head %}
Create a Question
{% endblock %}

{% block body %}
<form action ="{% url 'post:createpost' %}" method = "POST">
  {% csrf_token %}
  {% for field in form %}
   {{field.errors}}
   {{field.label}} {{ field }}
 {% endfor %}






<input type ="submit" value ="Create">

</form>
{% endblock %}

post/templates/index.html
{% extends 'base.html' %}

{% block head %}
 this is the index page
{% endblock %}

 {% block body %}
 <ol>
  {% for posts in posts %}
 <li>

     Post Content: {{ posts.content }}  <br />


 </li>

  {% endfor %}






 </ol>
 <a href = "{% url 'post:createpost' %}"> create post</a>



 {% endblock %}